import tkinter
from tkinter import *
from tkinter import messagebox
from tkinter import ttk
import pymysql
#t=tkinter.Tk()#make tkinter
#t.geometry('1700x1700')
def batchshiftinsert():
    def insertbatchs():
        db=pymysql.connect(host='localhost',user='root',password='root',database='institution')
        cur=db.cursor()
        a=e1.get()
        b=int(m.get())
        d=int(tu.get())
        e=int(w.get())
        g=int(th.get())
        h=int(f.get())
        x=int(sa.get())
        y=int(su.get())
        s="insert into batch_shift values('%s',%d,%d,%d,%d,%d,%d,%d)"%(a,b,d,e,g,h,x,y)
        cur.execute(s)
        db.commit()
        messagebox.showinfo("Data Saved","Saved..")
        e1.delete(0,100)
        m.delete(0,100)
        tu.delete(0,100)
        w.delete(0,100)
        th.delete(0,100)
        f.delete(0,100)
        sa.delete(0,100)
        su.delete(0,100)
        db.close()
        
    
    c=Canvas(width=1700,height=1700,bg='pink')
    c.place(x=500,y=0)
    a=Label(c,text="Batch Shift Details",font=('Bookman Old Style',20),width=25,height=3)
    a.place(x=350,y=70)
    l1=Label(c,text="Batch Shift Id",font=('TimesNewRoman'),width=15)
    l1.place(x=400,y=230)
    e1=Entry(c,width=30)
    e1.place(x=600,y=230,height=30)
    m=IntVar()
    tu=IntVar()
    w=IntVar()
    th=IntVar()
    f=IntVar()
    sa=IntVar()
    su=IntVar()
    c1=Checkbutton(c,text='Monday',font=('TimesNewRoman'),width=10,variable=m,onvalue=1,offvalue=0)
    c1.place(x=500,y=300)
    c2=Checkbutton(c,text='Tuesday',font=('TimesNewRoman'),width=10,variable=tu,onvalue=1,offvalue=0)
    c2.place(x=500,y=360)
    c3=Checkbutton(c,text='Wednesday',font=('TimesNewRoman'),width=10,variable=w,onvalue=1,offvalue=0)
    c3.place(x=500,y=420)
    c4=Checkbutton(c,text='Thursday',font=('TimesNewRoman'),width=10,variable=th,onvalue=1,offvalue=0)
    c4.place(x=500,y=480)
    c5=Checkbutton(c,text='Friday',font=('TimesNewRoman'),width=10,variable=f,onvalue=1,offvalue=0)
    c5.place(x=500,y=540)
    c6=Checkbutton(c,text='Saturday',font=('TimesNewRoman'),width=10,variable=sa,onvalue=1,offvalue=0)
    c6.place(x=500,y=600)
    c7=Checkbutton(c,text='Sunday',font=('TimesNewRoman'),width=10,variable=su,onvalue=1,offvalue=0)
    c7.place(x=500,y=660)
    #bt1=Button(c,text="save",font=('TimesNewRoman'),width=10)
    bt1=Button(c,text="Save",font=('Bookman Old Style',20),width=8,command=insertbatchs)
    bt1.place(x=300,y=680)
    bt2=Button(c,text="Close",font=('Bookman Old Style',20),width=8)
    bt2.place(x=700,y=680)
    
#bt=Button(t,text="save",command=batchshiftInsert)
#bt.place(x=50,y=50)
#t.mainloop()